version: "3"
services:
  mongo:
    container_name: mongo-quiz
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
    #command: [--auth]

volumes:
  mongodbdata:
